spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/study;
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false
    thymeleaf:
      cache: false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true #system.out.println을 통해서 나오기떄문에 주석 운영에서는 사용X
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace